[[headers]]
  for = "/.well-known/oauth-authorization-server"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/.well-known/oauth-protected-resource"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/.well-known/openid-configuration"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
