import { withMaterialColors } from 'tailwind-material-colors'

/** @type {import('tailwindcss').Config} */
const config = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Roboto', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-large':   ['57px', { lineHeight: '64px',  letterSpacing: '-0.25px' }],
        'display-medium':  ['45px', { lineHeight: '52px',  letterSpacing: '0px' }],
        'display-small':   ['36px', { lineHeight: '44px',  letterSpacing: '0px' }],
        'headline-large':  ['32px', { lineHeight: '40px',  letterSpacing: '-0.5px' }],
        'headline-medium': ['28px', { lineHeight: '36px',  letterSpacing: '-0.5px' }],
        'headline-small':  ['24px', { lineHeight: '32px',  letterSpacing: '-0.3px' }],
        'title-large':     ['22px', { lineHeight: '28px',  letterSpacing: '-0.3px' }],
        'title-medium':    ['16px', { lineHeight: '24px',  letterSpacing: '-0.1px' }],
        'title-small':     ['14px', { lineHeight: '20px',  letterSpacing: '0px' }],
        'body-large':      ['16px', { lineHeight: '24px',  letterSpacing: '0px' }],
        'body-medium':     ['14px', { lineHeight: '20px',  letterSpacing: '0px' }],
        'body-small':      ['12px', { lineHeight: '16px',  letterSpacing: '0px' }],
        'label-large':     ['14px', { lineHeight: '20px',  letterSpacing: '0px' }],
        'label-medium':    ['12px', { lineHeight: '16px',  letterSpacing: '0.5px' }],
        'label-small':     ['11px', { lineHeight: '16px',  letterSpacing: '0.5px' }],
      },
      borderRadius: {
        'xs':   '3px',
        'sm':   '6px',
        'md':   '10px',
        'lg':   '14px',
        'xl':   '20px',
        'pill': '9999px',
      },
      // Greyscale design tokens — use directly in new components
      colors: {
        // Red shades for delete buttons — defined explicitly because withMaterialColors overrides Tailwind's default palette
        'red-50':  '#fef2f2',
        'red-400': '#f87171',
        'red-500': '#ef4444',
        ink:      '#111111',
        'ink-2':  '#333333',
        mute:     '#6b6b6b',
        'mute-2': '#9a9a9a',
        line:     '#cfcfcf',
        'line-2': '#e6e6e6',
        surf:     '#f5f5f5',
        'surf-2': '#fafafa',
        paper:    '#ffffff',
        // MD3 semantic names — all remapped to greyscale via CSS vars in index.css
        'background':                 'var(--md-background)',
        'on-background':              'var(--md-on-background)',
        'surface':                    'var(--md-surface)',
        'surface-dim':                'var(--md-surface-dim)',
        'surface-bright':             'var(--md-surface-bright)',
        'surface-container-lowest':   'var(--md-surface-container-lowest)',
        'surface-container-low':      'var(--md-surface-container-low)',
        'surface-container':          'var(--md-surface-container)',
        'surface-container-high':     'var(--md-surface-container-high)',
        'surface-container-highest':  'var(--md-surface-container-highest)',
        'on-surface':                 'var(--md-on-surface)',
        'on-surface-variant':         'var(--md-on-surface-variant)',
        'surface-variant':            'var(--md-surface-variant)',
        'inverse-surface':            'var(--md-inverse-surface)',
        'on-inverse-surface':         'var(--md-on-inverse-surface)',
        'outline':                    'var(--md-outline)',
        'outline-variant':            'var(--md-outline-variant)',
        'primary':                    'var(--md-primary)',
        'on-primary':                 'var(--md-on-primary)',
        'primary-container':          'var(--md-primary-container)',
        'on-primary-container':       'var(--md-on-primary-container)',
        'inverse-primary':            'var(--md-inverse-primary)',
        'secondary':                  'var(--md-secondary)',
        'on-secondary':               'var(--md-on-secondary)',
        'secondary-container':        'var(--md-secondary-container)',
        'on-secondary-container':     'var(--md-on-secondary-container)',
        'tertiary':                   'var(--md-tertiary)',
        'on-tertiary':                'var(--md-on-tertiary)',
        'tertiary-container':         'var(--md-tertiary-container)',
        'on-tertiary-container':      'var(--md-on-tertiary-container)',
        'error':                      'var(--md-error)',
        'on-error':                   'var(--md-on-error)',
        'error-container':            'var(--md-error-container)',
        'on-error-container':         'var(--md-on-error-container)',
        'scrim':                      'var(--md-scrim)',
      },
    },
  },
  plugins: [],
}

export default withMaterialColors(config, { primary: '#1C1B1F' }, { scheme: 'tonal-spot', contrast: 0 })
