<?php

declare(strict_types=1);

namespace Tasker\Tests\Contract;

use PHPUnit\Framework\TestCase;
use Tasker\TaskerPlugin;
use Whity\Mcp\Tools\ToolDeriver;

/**
 * Asserts our derived MCP tool schemas against the ORIGINAL app's, for every
 * tool name present in both surfaces.
 *
 * This is what turns "we preserved the contract" from an assertion into a build
 * failure. D1 shipped 34 tools whose names matched the original and whose
 * argument shapes did not, and every acceptance check passed — this test exists
 * so that cannot recur silently.
 *
 * WHERE EACH SIDE COMES FROM
 *
 * Ours is DERIVED, not read from a snapshot. `docs/mcp-tool-surface.json` is
 * deliberately not consulted: regenerating it needs a live MCP host (which does
 * not currently build), so it is stale, and a test that depended on it could not
 * run in CI at all. Instead we instantiate core's real `ToolDeriver` against
 * `TaskerPlugin::getRoutes()` — the same class, the same route table, and the
 * same merge rules the host itself uses at tools/list time. Nothing about the
 * derivation is reimplemented here, which matters for one specific failure this
 * slice was created to catch: `ToolDeriver::buildInputSchema()` makes every path
 * parameter UNCONDITIONALLY REQUIRED, so a leftover `{id:\d+}` on any route
 * surfaces as a required property the original does not have, and this test
 * fails on it. A hand-rolled derivation would smooth that away.
 *
 * Theirs is a COMMITTED SNAPSHOT (`original-tool-schemas.json`), regenerated by
 * `host/scripts/extract-original-schemas.ps1`. Committing it rather than reading
 * across repos at test time is what keeps this hermetic. Read that file's
 * `_meta.sourceIsStale` before treating it as gospel — it is a floor on the
 * original's surface, corrected against a hand capture of the live server.
 *
 * WHAT IS COMPARED, AND WHY NOT MORE
 *
 *  - property NAMES, both directions;
 *  - `required`, ONE direction only — anything WE require that the original does
 *    not. The reverse is us being more permissive, which cannot break a caller;
 *  - `enum` VALUES, both directions, wherever both sides declare an enum for the
 *    same property. A `priority` or `status` that accepts a different vocabulary
 *    is a contract break that name comparison alone sails straight past.
 *
 * Descriptions and non-enum types are deliberately NOT compared: that direction
 * is all false positives.
 *
 * Divergences are allowed, but each must be listed in `parity-allowlist.php`
 * WITH a reason. An unlisted divergence fails — and so does a listed one that no
 * longer exists, so the allowlist has to shrink as routes get fixed rather than
 * accumulating dead entries that hide the next regression.
 *
 * NOT COVERED HERE: tools in OUR surface that the original has no tool for at
 * all (13 of our 49 — the ping scaffolding, `get_board`, `pin_task`/`unpin_task`,
 * `set_default_project`, the `update_*` siblings of the original's `rename_*`,
 * and the task-discussion pair). Those are additions rather than divergences and
 * this test says nothing about them.
 */
final class OriginalContractParityTest extends TestCase
{
    /**
     * Every original tool this plugin has not ported. Asserted so the size of
     * the gap cannot drift unnoticed in either direction — porting a tool must
     * come with a deliberate edit here, and so must losing one.
     *
     * 143 tools live on the original; 36 of them exist here; 107 do not.
     */
    private const EXPECTED_UNPORTED_COUNT = 107;

    /** The original's full live surface: 131 snapshotted + 12 known live-only names. */
    private const EXPECTED_ORIGINAL_SURFACE_SIZE = 143;

    public function testEverySharedToolMatchesTheOriginalsArgumentShape(): void
    {
        $original = self::originalSchemas();
        $ours     = self::ourSchemas();
        $allow    = require __DIR__ . '/parity-allowlist.php';

        self::assertNotSame([], $original, 'the original snapshot is empty');
        self::assertNotSame([], $ours, 'no tools were derived from the route table');

        $failures = [];

        foreach ($original as $name => $originalSchema) {
            if (!isset($ours[$name])) {
                continue; // Not ported — counted by the unported test below.
            }

            $entry = $allow[$name] ?? [];

            $expected = array_keys(self::properties($originalSchema));
            $actual   = array_keys(self::properties($ours[$name]));

            $missing = array_values(array_diff($expected, $actual, $entry['missing'] ?? []));
            $extra   = array_values(array_diff($actual, $expected, $entry['extra'] ?? []));

            if ($missing !== []) {
                $failures[] = "{$name}: missing properties the original accepts: " . implode(', ', $missing);
            }
            if ($extra !== []) {
                $failures[] = "{$name}: properties the original does not accept: " . implode(', ', $extra);
            }

            $newlyRequired = array_values(array_diff(
                self::requiredOf($ours[$name]),
                self::requiredOf($originalSchema),
                $entry['required'] ?? [],
            ));
            if ($newlyRequired !== []) {
                $failures[] = "{$name}: required but optional in the original: " . implode(', ', $newlyRequired);
            }

            foreach (self::enumDivergences($originalSchema, $ours[$name], $entry) as $message) {
                $failures[] = "{$name}: {$message}";
            }
        }

        foreach (self::staleAllowlistEntries($allow, $original, $ours) as $message) {
            $failures[] = $message;
        }

        self::assertSame(
            [],
            $failures,
            "Contract parity failures (fix the route, or allowlist it WITH a reason):\n  - "
            . implode("\n  - ", $failures) . "\n",
        );
    }

    /**
     * The unported slice of the original's surface.
     *
     * The parity test above skips original tools we do not implement, which is
     * right — but a silent skip hides how much of the contract is unported, and
     * a gap nobody can see is the failure mode this whole file exists to
     * prevent. This asserts the size of that gap so it cannot move without
     * somebody saying so.
     */
    public function testTheUnportedSliceOfTheOriginalSurfaceIsTheExpectedSize(): void
    {
        $ours = self::ourSchemas();

        /** @var list<string> $names */
        $names = array_merge(array_keys(self::originalSchemas()), self::liveOnlyToolNames());
        $unported = array_values(array_filter($names, static fn (string $n): bool => !isset($ours[$n])));
        sort($unported);

        self::assertCount(
            self::EXPECTED_UNPORTED_COUNT,
            $unported,
            sprintf(
                "The unported slice of the original's tool surface changed (expected %d, got %d).\n"
                . "If a slice ported one of these, lower EXPECTED_UNPORTED_COUNT in the same commit.\n"
                . "Unported:\n  %s\n",
                self::EXPECTED_UNPORTED_COUNT,
                count($unported),
                implode("\n  ", $unported),
            ),
        );

        self::assertCount(
            self::EXPECTED_ORIGINAL_SURFACE_SIZE,
            $names,
            'The snapshot of the original surface changed size — re-run '
            . 'host/scripts/extract-original-schemas.ps1 and re-verify the counts above.',
        );
    }

    // ── The two surfaces ─────────────────────────────────────────────────────

    /**
     * Our tool surface, derived exactly the way the host derives it.
     *
     * ToolDeriver caches its results in static properties for the lifetime of a
     * worker, so the caches are cleared on both sides of the call — otherwise
     * this test would either serve, or poison, another test's derivation.
     *
     * @return array<string, array<string, mixed>> tool name => inputSchema
     */
    private static function ourSchemas(): array
    {
        ToolDeriver::clearCache();
        try {
            $deriver = new ToolDeriver(
                (new TaskerPlugin())->getRoutes(),
                [],
                null,
                // ToolDeriver's default warn closure is error_log(). Swallow it:
                // its mutation-body lint is not what this test measures, and
                // PHPUnit is configured failOnWarning.
                static function (string $message): void {
                },
            );
            $tools = $deriver->deriveTools();
        } finally {
            ToolDeriver::clearCache();
        }

        $byName = [];
        foreach ($tools as $tool) {
            $byName[(string) $tool['name']] = is_array($tool['inputSchema'] ?? null) ? $tool['inputSchema'] : [];
        }
        ksort($byName);

        return $byName;
    }

    /** @return array<string, array<string, mixed>> tool name => inputSchema */
    private static function originalSchemas(): array
    {
        /** @var array<string, mixed> $doc */
        $doc = self::snapshot();
        /** @var array<string, array<string, mixed>> $tools */
        $tools = is_array($doc['tools'] ?? null) ? $doc['tools'] : [];

        return $tools;
    }

    /** @return list<string> */
    private static function liveOnlyToolNames(): array
    {
        $doc = self::snapshot();
        /** @var list<string> $names */
        $names = is_array($doc['liveOnlyToolNames'] ?? null) ? array_values($doc['liveOnlyToolNames']) : [];

        return $names;
    }

    /** @return array<string, mixed> */
    private static function snapshot(): array
    {
        $raw = file_get_contents(__DIR__ . '/original-tool-schemas.json');
        self::assertIsString($raw, 'original-tool-schemas.json is unreadable');
        $doc = json_decode($raw, true);
        self::assertIsArray($doc, 'original-tool-schemas.json is not valid JSON');

        return $doc;
    }

    // ── Comparison helpers ───────────────────────────────────────────────────

    /**
     * @param array<string, mixed> $schema
     * @return array<string, array<string, mixed>>
     */
    private static function properties(array $schema): array
    {
        /** @var array<string, array<string, mixed>> $props */
        $props = is_array($schema['properties'] ?? null) ? $schema['properties'] : [];

        return $props;
    }

    /**
     * @param array<string, mixed> $schema
     * @return list<string>
     */
    private static function requiredOf(array $schema): array
    {
        $required = is_array($schema['required'] ?? null) ? $schema['required'] : [];

        return array_values(array_filter($required, 'is_string'));
    }

    /**
     * Enum vocabularies that differ, in either direction, for a property both
     * sides declare an enum for.
     *
     * Compared with strict in_array rather than array_diff because our enums
     * carry literal nulls (the "clear this field" form) and array_diff compares
     * by string cast, which would silently equate null with "".
     *
     * @param array<string, mixed> $originalSchema
     * @param array<string, mixed> $ourSchema
     * @param array<string, mixed> $entry allowlist entry for this tool
     * @return list<string>
     */
    private static function enumDivergences(array $originalSchema, array $ourSchema, array $entry): array
    {
        $theirProps = self::properties($originalSchema);
        $ourProps   = self::properties($ourSchema);

        /** @var array<string, list<mixed>> $allowMissing */
        $allowMissing = is_array($entry['enumMissing'] ?? null) ? $entry['enumMissing'] : [];
        /** @var array<string, list<mixed>> $allowExtra */
        $allowExtra = is_array($entry['enumExtra'] ?? null) ? $entry['enumExtra'] : [];

        $messages = [];
        foreach ($theirProps as $property => $theirProp) {
            $ourProp = $ourProps[$property] ?? null;
            if (!is_array($ourProp)) {
                continue;
            }
            $theirEnum = $theirProp['enum'] ?? null;
            $ourEnum   = $ourProp['enum'] ?? null;
            if (!is_array($theirEnum) || !is_array($ourEnum)) {
                continue;
            }

            $missing = self::valuesNotIn($theirEnum, $ourEnum, $allowMissing[$property] ?? []);
            if ($missing !== []) {
                $messages[] = "{$property} rejects enum values the original accepts: " . self::render($missing);
            }

            $extra = self::valuesNotIn($ourEnum, $theirEnum, $allowExtra[$property] ?? []);
            if ($extra !== []) {
                $messages[] = "{$property} accepts enum values the original does not: " . self::render($extra);
            }
        }

        return $messages;
    }

    /**
     * @param array<int|string, mixed> $candidates
     * @param array<int|string, mixed> $present
     * @param array<int|string, mixed> $allowed
     * @return list<mixed>
     */
    private static function valuesNotIn(array $candidates, array $present, array $allowed): array
    {
        return array_values(array_filter(
            $candidates,
            static fn (mixed $v): bool => !in_array($v, $present, true) && !in_array($v, $allowed, true),
        ));
    }

    /** @param list<mixed> $values */
    private static function render(array $values): string
    {
        return implode(', ', array_map(
            static fn (mixed $v): string => (string) json_encode($v),
            $values,
        ));
    }

    // ── Allowlist hygiene ────────────────────────────────────────────────────

    /**
     * An allowlist entry that no longer describes a real divergence is worse
     * than no entry: it is a hole in the net, sitting exactly where somebody
     * already decided divergence was tolerable. Every entry must be live, and
     * must carry a reason a human wrote.
     *
     * @param array<string, mixed>                  $allow
     * @param array<string, array<string, mixed>>   $original
     * @param array<string, array<string, mixed>>   $ours
     * @return list<string>
     */
    private static function staleAllowlistEntries(array $allow, array $original, array $ours): array
    {
        $failures = [];

        foreach ($allow as $name => $entry) {
            if (!is_array($entry)) {
                $failures[] = "allowlist[{$name}] is not an array";
                continue;
            }
            if (!is_string($entry['reason'] ?? null) || trim((string) $entry['reason']) === '') {
                $failures[] = "allowlist[{$name}] has no reason — an entry whose reason cannot be stated is a bug to fix, not a line to add";
            }
            if (!isset($original[$name])) {
                $failures[] = "allowlist[{$name}] names a tool the original does not have";
                continue;
            }
            if (!isset($ours[$name])) {
                $failures[] = "allowlist[{$name}] names a tool we do not implement — nothing to diverge from";
                continue;
            }

            $theirProps = array_keys(self::properties($original[$name]));
            $ourProps   = array_keys(self::properties($ours[$name]));

            foreach (self::listOf($entry, 'missing') as $property) {
                if (in_array($property, $ourProps, true) || !in_array($property, $theirProps, true)) {
                    $failures[] = "allowlist[{$name}].missing lists '{$property}', which is no longer missing";
                }
            }
            foreach (self::listOf($entry, 'extra') as $property) {
                if (!in_array($property, $ourProps, true) || in_array($property, $theirProps, true)) {
                    $failures[] = "allowlist[{$name}].extra lists '{$property}', which is no longer extra";
                }
            }
            foreach (self::listOf($entry, 'required') as $property) {
                if (!in_array($property, self::requiredOf($ours[$name]), true)
                    || in_array($property, self::requiredOf($original[$name]), true)
                ) {
                    $failures[] = "allowlist[{$name}].required lists '{$property}', which we no longer require alone";
                }
            }

            // Enum waivers: check the waived value is still on the side claimed.
            foreach (['enumMissing' => [$original[$name], $ours[$name]], 'enumExtra' => [$ours[$name], $original[$name]]] as $key => [$has, $lacks]) {
                /** @var array<string, list<mixed>> $waivers */
                $waivers = is_array($entry[$key] ?? null) ? $entry[$key] : [];
                foreach ($waivers as $property => $values) {
                    $hasEnum   = self::properties($has)[$property]['enum'] ?? null;
                    $lacksEnum = self::properties($lacks)[$property]['enum'] ?? null;
                    foreach ($values as $value) {
                        $stillDiverges = is_array($hasEnum) && in_array($value, $hasEnum, true)
                            && (!is_array($lacksEnum) || !in_array($value, $lacksEnum, true));
                        if (!$stillDiverges) {
                            $failures[] = sprintf(
                                "allowlist[%s].%s['%s'] waives %s, which is no longer a divergence",
                                $name,
                                $key,
                                $property,
                                (string) json_encode($value),
                            );
                        }
                    }
                }
            }
        }

        return $failures;
    }

    /**
     * @param array<string, mixed> $entry
     * @return list<string>
     */
    private static function listOf(array $entry, string $key): array
    {
        $values = is_array($entry[$key] ?? null) ? $entry[$key] : [];

        return array_values(array_filter($values, 'is_string'));
    }
}
