<?php

declare(strict_types=1);

namespace Tasker\Tests\Contract;

use PHPUnit\Framework\TestCase;
use Tasker\TaskerPlugin;
use Whity\Mcp\Tools\ToolDeriver;

/**
 * Asserts our derived MCP tool schemas against the ORIGINAL app's, for every
 * tool name present in both surfaces.
 *
 * This is what turns "we preserved the contract" from an assertion into a build
 * failure. D1 shipped 34 tools whose names matched the original and whose
 * argument shapes did not, and every acceptance check passed — this test exists
 * so that cannot recur silently.
 *
 * WHERE EACH SIDE COMES FROM
 *
 * Ours is DERIVED, not read from a snapshot. `docs/mcp-tool-surface.json` is
 * deliberately not consulted: regenerating it needs a live MCP host (which does
 * not currently build), so it is stale, and a test that depended on it could not
 * run in CI at all. Instead we instantiate core's real `ToolDeriver` against
 * `TaskerPlugin::getRoutes()` — the same class, the same route table, and the
 * same merge rules the host itself uses at tools/list time. Nothing about the
 * derivation is reimplemented here, which matters for one specific failure this
 * slice was created to catch: `ToolDeriver::buildInputSchema()` makes every path
 * parameter UNCONDITIONALLY REQUIRED, so a leftover `{id:\d+}` on any route
 * surfaces as a required property the original does not have, and this test
 * fails on it. A hand-rolled derivation would smooth that away.
 *
 * Theirs is a COMMITTED SNAPSHOT (`original-tool-schemas.json`), regenerated by
 * `host/scripts/extract-original-schemas.ps1`. Committing it rather than reading
 * across repos at test time is what keeps this hermetic. Read that file's
 * `_meta.sourceIsStale` before treating it as gospel — it is a floor on the
 * original's surface, corrected against a hand capture of the live server.
 *
 * WHAT IS COMPARED, AND WHY NOT MORE
 *
 *  - property NAMES, both directions;
 *  - `required`, ONE direction only — anything WE require that the original does
 *    not. The reverse is us being more permissive, which cannot break a caller;
 *  - `enum` VALUES, both directions, wherever both sides declare an enum for the
 *    same property. A `priority` or `status` that accepts a different vocabulary
 *    is a contract break that name comparison alone sails straight past.
 *
 * Descriptions and non-enum types are deliberately NOT compared: that direction
 * is all false positives.
 *
 * Divergences are allowed, but each must be listed in `parity-allowlist.php`
 * WITH a reason. An unlisted divergence fails — and so does a listed one that no
 * longer exists, so the allowlist has to shrink as routes get fixed rather than
 * accumulating dead entries that hide the next regression.
 *
 * NOT COVERED HERE: tools in OUR surface that the original has no tool for at
 * all (13 of our 55 — the ping scaffolding, `get_board`, `pin_task`/`unpin_task`,
 * `set_default_project`, the `update_*` siblings of the original's `rename_*`,
 * and the task-discussion pair). Those are additions rather than divergences and
 * this test says nothing about them.
 */
final class OriginalContractParityTest extends TestCase
{
    /**
     * Every original tool this plugin has not ported. Asserted so the size of
     * the gap cannot drift unnoticed in either direction — porting a tool must
     * come with a deliberate edit here, and so must losing one.
     *
     * 143 tools live on the original; 42 of them exist here; 101 do not.
     * D5a Task 5 ported name_flow/list_flows/delete_flow (107 -> 104). D5a
     * Task 6 ported get_flow_context/update_flow_context/build_new_flow
     * (104 -> 101).
     */
    private const EXPECTED_UNPORTED_COUNT = 101;

    /** The original's full live surface: 131 snapshotted + 12 known live-only names. */
    private const EXPECTED_ORIGINAL_SURFACE_SIZE = 143;

    public function testEverySharedToolMatchesTheOriginalsArgumentShape(): void
    {
        $original = self::originalSchemas();
        $ours     = self::ourSchemas();
        $allow    = require __DIR__ . '/parity-allowlist.php';

        self::assertNotSame([], $original, 'the original snapshot is empty');
        self::assertNotSame([], $ours, 'no tools were derived from the route table');

        $failures = [];

        foreach ($original as $name => $originalSchema) {
            if (!isset($ours[$name])) {
                continue; // Not ported — counted by the unported test below.
            }

            $entry = $allow[$name] ?? [];

            $expected = array_keys(self::properties($originalSchema));
            $actual   = array_keys(self::properties($ours[$name]));

            $missing = array_values(array_diff($expected, $actual, $entry['missing'] ?? []));
            $extra   = array_values(array_diff($actual, $expected, $entry['extra'] ?? []));

            if ($missing !== []) {
                $failures[] = "{$name}: missing properties the original accepts: " . implode(', ', $missing);
            }
            if ($extra !== []) {
                $failures[] = "{$name}: properties the original does not accept: " . implode(', ', $extra);
            }

            $newlyRequired = array_values(array_diff(
                self::requiredOf($ours[$name]),
                self::requiredOf($originalSchema),
                $entry['required'] ?? [],
            ));
            if ($newlyRequired !== []) {
                $failures[] = "{$name}: required but optional in the original: " . implode(', ', $newlyRequired);
            }

            foreach (self::enumDivergences($originalSchema, $ours[$name], $entry) as $message) {
                $failures[] = "{$name}: {$message}";
            }
        }

        foreach (self::staleAllowlistEntries($allow, $original, $ours) as $message) {
            $failures[] = $message;
        }

        self::assertSame(
            [],
            $failures,
            "Contract parity failures (fix the route, or allowlist it WITH a reason):\n  - "
            . implode("\n  - ", $failures) . "\n",
        );
    }

    /**
     * The unported slice of the original's surface.
     *
     * The parity test above skips original tools we do not implement, which is
     * right — but a silent skip hides how much of the contract is unported, and
     * a gap nobody can see is the failure mode this whole file exists to
     * prevent. This asserts the size of that gap so it cannot move without
     * somebody saying so.
     */
    public function testTheUnportedSliceOfTheOriginalSurfaceIsTheExpectedSize(): void
    {
        $ours = self::ourSchemas();

        /** @var list<string> $names */
        $names = array_merge(array_keys(self::originalSchemas()), self::liveOnlyToolNames());
        $unported = array_values(array_filter($names, static fn (string $n): bool => !isset($ours[$n])));
        sort($unported);

        $direction = count($unported) < self::EXPECTED_UNPORTED_COUNT
            ? "The gap SHRANK. If a slice ported one of these, lower EXPECTED_UNPORTED_COUNT in the same commit.\n"
                . "If it ported one of the liveOnlyToolNames, capture that tool's real schema from the live server\n"
                . "first — the snapshot has its name but not its shape, so nothing can check the port against it."
            : "The gap GREW. Either a tool was REMOVED from our surface (check the route table for a lost\n"
                . "operationId — mcp-tools.ps1's allowlist should have caught it too), or the snapshot gained tools\n"
                . 'because the generator was re-run against a newer source. Those need opposite responses: the first '
                . "is a regression to revert, the second is a real increase to record.";

        self::assertCount(
            self::EXPECTED_UNPORTED_COUNT,
            $unported,
            sprintf(
                "The unported slice of the original's tool surface changed (expected %d, got %d).\n%s\nUnported:\n  %s\n",
                self::EXPECTED_UNPORTED_COUNT,
                count($unported),
                $direction,
                implode("\n  ", $unported),
            ),
        );
    }

    /**
     * The size of the snapshot itself.
     *
     * Its own test rather than a second assertion on the unported one: it guards
     * a different regression (the snapshot losing or gaining tools) and, sharing
     * a method, it would never run on the turn the unported count failed — which
     * is exactly the turn its answer matters most.
     */
    public function testTheSnapshotStillDescribesTheWholeOriginalSurface(): void
    {
        $names = array_merge(array_keys(self::originalSchemas()), self::liveOnlyToolNames());

        self::assertCount(
            self::EXPECTED_ORIGINAL_SURFACE_SIZE,
            $names,
            sprintf(
                'The snapshot of the original surface changed size (expected %d, got %d). Re-run '
                . 'host/scripts/extract-original-schemas.ps1, check _meta.sourceIsStale against the live server, '
                . 'and re-verify EXPECTED_UNPORTED_COUNT in the same commit.',
                self::EXPECTED_ORIGINAL_SURFACE_SIZE,
                count($names),
            ),
        );
    }

    // ── The two surfaces ─────────────────────────────────────────────────────

    /**
     * Our tool surface, derived exactly the way the host derives it.
     *
     * ToolDeriver caches its results in static properties for the lifetime of a
     * worker, so the caches are cleared on both sides of the call — otherwise
     * this test would either serve, or poison, another test's derivation.
     *
     * @return array<string, array<string, mixed>> tool name => inputSchema
     */
    private static function ourSchemas(): array
    {
        ToolDeriver::clearCache();
        try {
            $deriver = new ToolDeriver(
                (new TaskerPlugin())->getRoutes(),
                [],
                null,
                // ToolDeriver's default warn closure is error_log(). Swallow it:
                // its mutation-body lint fires on routes this test has no
                // opinion about, and routing that into the run's error log is
                // noise at best. Nothing here depends on what it would say.
                static function (string $message): void {
                },
            );
            $tools = $deriver->deriveTools();
        } finally {
            ToolDeriver::clearCache();
        }

        $byName = [];
        foreach ($tools as $tool) {
            $byName[(string) $tool['name']] = is_array($tool['inputSchema'] ?? null) ? $tool['inputSchema'] : [];
        }
        ksort($byName);

        return $byName;
    }

    /** @return array<string, array<string, mixed>> tool name => inputSchema */
    private static function originalSchemas(): array
    {
        /** @var array<string, mixed> $doc */
        $doc = self::snapshot();
        /** @var array<string, array<string, mixed>> $tools */
        $tools = is_array($doc['tools'] ?? null) ? $doc['tools'] : [];

        return $tools;
    }

    /** @return list<string> */
    private static function liveOnlyToolNames(): array
    {
        $doc = self::snapshot();
        /** @var list<string> $names */
        $names = is_array($doc['liveOnlyToolNames'] ?? null) ? array_values($doc['liveOnlyToolNames']) : [];

        return $names;
    }

    /** @return array<string, mixed> */
    private static function snapshot(): array
    {
        $raw = file_get_contents(__DIR__ . '/original-tool-schemas.json');
        self::assertIsString($raw, 'original-tool-schemas.json is unreadable');
        $doc = json_decode($raw, true);
        self::assertIsArray($doc, 'original-tool-schemas.json is not valid JSON');

        return $doc;
    }

    // ── Comparison helpers ───────────────────────────────────────────────────

    /**
     * @param array<string, mixed> $schema
     * @return array<string, array<string, mixed>>
     */
    private static function properties(array $schema): array
    {
        /** @var array<string, array<string, mixed>> $props */
        $props = is_array($schema['properties'] ?? null) ? $schema['properties'] : [];

        return $props;
    }

    /**
     * @param array<string, mixed> $schema
     * @return list<string>
     */
    private static function requiredOf(array $schema): array
    {
        $required = is_array($schema['required'] ?? null) ? $schema['required'] : [];

        return array_values(array_filter($required, 'is_string'));
    }

    /**
     * Enum vocabularies that differ, in either direction, for a property both
     * sides declare an enum for.
     *
     * Compared with strict in_array rather than array_diff because our enums
     * carry literal nulls (the "clear this field" form) and array_diff compares
     * by string cast, which would silently equate null with "".
     *
     * @param array<string, mixed> $originalSchema
     * @param array<string, mixed> $ourSchema
     * @param array<string, mixed> $entry allowlist entry for this tool
     * @return list<string>
     */
    private static function enumDivergences(array $originalSchema, array $ourSchema, array $entry): array
    {
        $theirProps = self::properties($originalSchema);
        $ourProps   = self::properties($ourSchema);

        /** @var array<string, list<mixed>> $allowMissing */
        $allowMissing = is_array($entry['enumMissing'] ?? null) ? $entry['enumMissing'] : [];
        /** @var array<string, list<mixed>> $allowExtra */
        $allowExtra = is_array($entry['enumExtra'] ?? null) ? $entry['enumExtra'] : [];

        $messages = [];
        foreach ($theirProps as $property => $theirProp) {
            $ourProp = $ourProps[$property] ?? null;
            if (!is_array($ourProp)) {
                continue;
            }
            $theirEnum = $theirProp['enum'] ?? null;
            $ourEnum   = $ourProp['enum'] ?? null;
            if (!is_array($theirEnum) || !is_array($ourEnum)) {
                continue;
            }

            $missing = self::valuesNotIn($theirEnum, $ourEnum, $allowMissing[$property] ?? []);
            if ($missing !== []) {
                $messages[] = "{$property} rejects enum values the original accepts: " . self::render($missing);
            }

            $extra = self::valuesNotIn($ourEnum, $theirEnum, $allowExtra[$property] ?? []);
            if ($extra !== []) {
                $messages[] = "{$property} accepts enum values the original does not: " . self::render($extra);
            }
        }

        return $messages;
    }

    /**
     * @param array<int|string, mixed> $candidates
     * @param array<int|string, mixed> $present
     * @param array<int|string, mixed> $allowed
     * @return list<mixed>
     */
    private static function valuesNotIn(array $candidates, array $present, array $allowed): array
    {
        return array_values(array_filter(
            $candidates,
            static fn (mixed $v): bool => !in_array($v, $present, true) && !in_array($v, $allowed, true),
        ));
    }

    /** @param list<mixed> $values */
    private static function render(array $values): string
    {
        return implode(', ', array_map(
            static fn (mixed $v): string => (string) json_encode($v),
            $values,
        ));
    }

    // ── Allowlist hygiene ────────────────────────────────────────────────────

    /**
     * An allowlist entry that no longer describes a real divergence is worse
     * than no entry: it is a hole in the net, sitting exactly where somebody
     * already decided divergence was tolerable. Every entry must be live, and
     * must carry a reason a human wrote.
     *
     * THE SEMANTIC RULE. Every SEMANTIC divergence in this file is expressed as
     * a `missing` property, which left an escape hatch worth naming: declaring
     * `delete_tasks` on delete_section's schema makes the entry stale, forces
     * its removal, and turns the build green — with the behaviour unchanged and
     * now MORE dangerous, because the caller believes the flag is honoured
     * where today it at least fails visibly as "not accepted" (core drops
     * undeclared arguments). A guard that can be satisfied by making the
     * problem invisible is not a guard.
     *
     * So a `severity: 'semantic'` entry inverts the staleness rule: declaring
     * the property is a FAILURE, not a discharge, unless the behavioural test
     * named in `dischargedBy` actually exists. Only once that test is in the
     * suite does the entry become removable — and removing it is then a
     * deliberate edit next to the comment explaining the semantics, which is
     * the whole point.
     *
     * @param array<string, mixed>                  $allow
     * @param array<string, array<string, mixed>>   $original
     * @param array<string, array<string, mixed>>   $ours
     * @return list<string>
     */
    private static function staleAllowlistEntries(array $allow, array $original, array $ours): array
    {
        $failures = [];

        foreach ($allow as $name => $entry) {
            if (!is_array($entry)) {
                $failures[] = "allowlist[{$name}] is not an array";
                continue;
            }
            if (!is_string($entry['reason'] ?? null) || trim((string) $entry['reason']) === '') {
                $failures[] = "allowlist[{$name}] has no reason — an entry whose reason cannot be stated is a bug to fix, not a line to add";
            }

            $isSemantic = ($entry['severity'] ?? null) === 'semantic';
            $dischargedBy = is_string($entry['dischargedBy'] ?? null) ? trim($entry['dischargedBy']) : '';
            if ($isSemantic && $dischargedBy === '') {
                $failures[] = "allowlist[{$name}] is severity 'semantic' but names no dischargedBy test. A semantic "
                    . 'divergence is a behaviour difference; it must name the behavioural test that has to exist '
                    . 'before the entry may be removed, so it cannot be discharged by a schema declaration alone.';
            }

            if (!isset($original[$name])) {
                $failures[] = "allowlist[{$name}] names a tool the original does not have";
                continue;
            }
            if (!isset($ours[$name])) {
                $failures[] = "allowlist[{$name}] names a tool we do not implement — nothing to diverge from";
                continue;
            }

            $theirProps = array_keys(self::properties($original[$name]));
            $ourProps   = array_keys(self::properties($ours[$name]));

            foreach (self::listOf($entry, 'missing') as $property) {
                if (!in_array($property, $theirProps, true)) {
                    $failures[] = "allowlist[{$name}].missing lists '{$property}', which the original does not have";
                    continue;
                }
                if (!in_array($property, $ourProps, true)) {
                    continue; // Still missing — the waiver is live.
                }

                // We now declare it. For an ordinary waiver that is a discharge.
                // For a SEMANTIC one it is only a discharge if the behaviour
                // actually landed, which is what dischargedBy has to prove.
                if (!$isSemantic || self::behaviourTestExists($dischargedBy)) {
                    $failures[] = "allowlist[{$name}].missing lists '{$property}', which is no longer missing";
                    continue;
                }

                $failures[] = sprintf(
                    "allowlist[%s].missing lists '%s', which our schema NOW DECLARES while the behaviour it "
                    . 'describes is still unimplemented — and no test named %s() exists to show otherwise. '
                    . 'Declaring the property does not discharge a SEMANTIC divergence; it makes it worse, because '
                    . 'the caller now believes the flag is honoured instead of seeing it rejected as unaccepted. '
                    . 'Implement the behaviour and add %s(), or revert the schema declaration.',
                    $name,
                    $property,
                    $dischargedBy === '' ? '<dischargedBy unset>' : $dischargedBy,
                    $dischargedBy === '' ? '<dischargedBy unset>' : $dischargedBy,
                );
            }
            foreach (self::listOf($entry, 'extra') as $property) {
                if (!in_array($property, $ourProps, true) || in_array($property, $theirProps, true)) {
                    $failures[] = "allowlist[{$name}].extra lists '{$property}', which is no longer extra";
                }
            }
            foreach (self::listOf($entry, 'required') as $property) {
                if (!in_array($property, self::requiredOf($ours[$name]), true)
                    || in_array($property, self::requiredOf($original[$name]), true)
                ) {
                    $failures[] = "allowlist[{$name}].required lists '{$property}', which we no longer require alone";
                }
            }

            // Enum waivers: check the waived value is still on the side claimed.
            foreach (['enumMissing' => [$original[$name], $ours[$name]], 'enumExtra' => [$ours[$name], $original[$name]]] as $key => [$has, $lacks]) {
                /** @var array<string, list<mixed>> $waivers */
                $waivers = is_array($entry[$key] ?? null) ? $entry[$key] : [];
                foreach ($waivers as $property => $values) {
                    $hasEnum   = self::properties($has)[$property]['enum'] ?? null;
                    $lacksEnum = self::properties($lacks)[$property]['enum'] ?? null;
                    foreach ($values as $value) {
                        $stillDiverges = is_array($hasEnum) && in_array($value, $hasEnum, true)
                            && (!is_array($lacksEnum) || !in_array($value, $lacksEnum, true));
                        if (!$stillDiverges) {
                            $failures[] = sprintf(
                                "allowlist[%s].%s['%s'] waives %s, which is no longer a divergence",
                                $name,
                                $key,
                                $property,
                                (string) json_encode($value),
                            );
                        }
                    }
                }
            }
        }

        return $failures;
    }

    /**
     * Does a test method of this name exist anywhere in the suite, AND does
     * its body contain at least one real assertion?
     *
     * This is what stops a SEMANTIC waiver being discharged by a schema edit:
     * the named behavioural test has to be real and in the tree before the
     * property may appear on our side without failing.
     *
     * REGRESSION FIX (review round 1 finding, first pass): the previous
     * version only checked `str_contains($source, "function {$method}(")` —
     * satisfied by declaring the waived property, adding an EMPTY-BODIED
     * method with the matching `dischargedBy` name, and deleting the
     * now-stale allowlist entry. That sequence made staleAllowlistEntries()
     * pass — the method existed — while the behaviour it claimed to prove was
     * never implemented, and the whole suite still went green. The method's
     * own BODY must contain at least one call that looks like
     * `assertSomething(` or `expectException(` — the two forms this
     * codebase's own tests actually use (see
     * ShortIdAllocatorTest::testWithRetryDoesNotTreatAnUnrelatedConstraintViolationAsARace()
     * for a real expectException()-only example) — before the method counts
     * as a genuine behavioural test.
     *
     * REGRESSION FIX (review round 1 finding, SECOND pass): the first pass's
     * own {@see self::methodBody()} had two more holes review found, both in
     * THIS file: (1) it matched the assertion regex against RAW body text, so
     * a body containing only `{ /* assertSame() would go here *\/ }` — the
     * exact false-positive shape a lazy discharge could produce — passed;
     * (2) it found the FIRST textual match of `function <name>(` anywhere in
     * the file, including inside a comment or docblock — this very
     * docblock's own prose (two paragraphs up, describing the empty-stub
     * regression by name) is itself now a live example: it is english text
     * ABOUT a method signature, not one, and a naive scan could confuse the
     * two. Fixed by tokenizing with `token_get_all()` (see methodBody()'s
     * own doc) instead of scanning raw characters: it locates a REAL
     * `T_FUNCTION` declaration whose name token matches $method (never text
     * inside a `T_COMMENT`/`T_DOC_COMMENT`, which are their own token kinds,
     * not raw substrings), and the reconstructed body it returns has every
     * comment and string-literal token already stripped, so the assertion
     * regex can only match a genuine token sequence, never a comment or a
     * string that merely mentions one.
     *
     * NOT AIRTIGHT, deliberately not claimed to be: nothing here can prove the
     * assertion checks the RIGHT thing, only that some assertion exists. A
     * method that asserts `self::assertTrue(true)` still passes this check.
     * It closes the specific gaps review demonstrated — it is not, and cannot
     * be, a substitute for actually reading the test when discharging an
     * entry.
     */
    private static function behaviourTestExists(string $method): bool
    {
        if ($method === '') {
            return false;
        }

        foreach (self::testFiles() as $file) {
            $source = file_get_contents($file);
            if (!is_string($source) || !str_contains($source, "function {$method}(")) {
                continue;
            }

            $body = self::methodBody($source, $method);
            if ($body !== null && preg_match('/\b(assert[A-Za-z]*|expectException)\s*\(/', $body) === 1) {
                return true;
            }
        }

        return false;
    }

    /**
     * The text of $method's real body — between its OWN opening `{` and its
     * matching closing `}` — with every comment and string-literal TOKEN
     * already stripped, so a body that only ever MENTIONS an assertion (in a
     * comment, or inside a string) can never be confused with one that
     * actually CALLS one.
     *
     * Uses `token_get_all()` rather than scanning raw characters (review
     * round 1, second pass — see behaviourTestExists()'s own docblock for
     * the two holes this closes): PHP's tokenizer already knows the
     * difference between a `T_FUNCTION` declaration, a `T_COMMENT`, and a
     * `T_STRING` identifier, so this walks tokens looking for a REAL
     * function declaration whose name token equals $method exactly (never a
     * textual match inside a comment/docblock/string — which are their own
     * distinct token kinds here, not raw substrings the way the previous,
     * character-scanning version treated them), then brace-counts at the
     * TOKEN level from its opening `{` (a `{`/`}` inside a comment or string
     * is already folded into that ONE token, so it can never be
     * miscounted as a real brace the way scanning raw characters could
     * risk). The first (topmost) matching declaration in the file wins,
     * matching every other file/method lookup in this class.
     *
     * @return string|null the reconstructed body (comments/strings removed,
     *         everything else — including whitespace — left as-is), or null
     *         if $method has no real declaration with a body in $source.
     */
    private static function methodBody(string $source, string $method): ?string
    {
        $tokens = token_get_all("<?php\n" . $source);
        $count = count($tokens);

        for ($i = 0; $i < $count; $i++) {
            $token = $tokens[$i];
            if (!is_array($token) || $token[0] !== T_FUNCTION) {
                continue;
            }

            $nameIndex = $i + 1;
            while ($nameIndex < $count && is_array($tokens[$nameIndex]) && in_array($tokens[$nameIndex][0], [T_WHITESPACE, T_COMMENT, T_DOC_COMMENT], true)) {
                $nameIndex++;
            }
            if (!is_array($tokens[$nameIndex]) || $tokens[$nameIndex][0] !== T_STRING || $tokens[$nameIndex][1] !== $method) {
                continue; // Not a declaration of $method (could be a closure, a different method, or unrelated).
            }

            // Advance past the signature (parameter list, return type) to
            // this declaration's own opening brace. A bare `;` first means
            // an abstract/interface method — no body to check.
            $openBrace = null;
            for ($j = $nameIndex + 1; $j < $count; $j++) {
                $text = is_array($tokens[$j]) ? $tokens[$j][1] : $tokens[$j];
                if ($text === '{') {
                    $openBrace = $j;
                    break;
                }
                if ($text === ';') {
                    return null;
                }
            }
            if ($openBrace === null) {
                return null;
            }

            $depth = 1;
            $body = '';
            for ($k = $openBrace + 1; $k < $count; $k++) {
                $token = $tokens[$k];
                $text = is_array($token) ? $token[1] : $token;

                if ($text === '{') {
                    $depth++;
                } elseif ($text === '}') {
                    $depth--;
                    if ($depth === 0) {
                        return $body;
                    }
                }

                // Comments and string-literal tokens are dropped entirely —
                // see this method's own docblock for why.
                if (is_array($token) && in_array(
                    $token[0],
                    [T_COMMENT, T_DOC_COMMENT, T_CONSTANT_ENCAPSED_STRING, T_ENCAPSED_AND_WHITESPACE],
                    true
                )) {
                    continue;
                }

                $body .= $text;
            }

            return null; // Unbalanced braces -- malformed source.
        }

        return null;
    }

    /** @return list<string> */
    private static function testFiles(): array
    {
        $files = [];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator(dirname(__DIR__), \FilesystemIterator::SKIP_DOTS),
        );
        /** @var \SplFileInfo $file */
        foreach ($iterator as $file) {
            if ($file->isFile() && $file->getExtension() === 'php') {
                $files[] = $file->getPathname();
            }
        }

        return $files;
    }

    /**
     * @param array<string, mixed> $entry
     * @return list<string>
     */
    private static function listOf(array $entry, string $key): array
    {
        $values = is_array($entry[$key] ?? null) ? $entry[$key] : [];

        return array_values(array_filter($values, 'is_string'));
    }
}
